### ISSUE TITLE
Bug: if statement in writeStoreFront function

### ISSUE THREAD

**Issue by aditya172926** [FresaClubWallet/fresaclub-contract#2]
Bug description:
The if statement (line 42) in function `writeStoreFront()` checks that the store should not already exist corresponding address and if the store exists, it prevents the `fresaStoreCount` to increment.

This does not stop the rest of the function to execute, because if the `fresaStoreCount` does not increment, it does not revert the function. The further execution of this function can replace an already existing store in the `storeFronts` mapping, with a new store.

**Comment by aditya172926** [comment]
I am closing this issue as this is no longer relevant.

**Comment by MatWaller** [comment]
Posting this comment for future developers to see.

Calling `writeStorefront` for the first time is designed to increment the storefront count.

Following calls to this function edit an existing storefront without incrementing the storefront count this is done by design as having a seperate edit function would bloat the contract is size - which is something we would like to avoid.
